export const API_RUNTIME_KEYS = [
  "APP_URL", "DATABASE_URL", "BETTER_AUTH_SECRET",
  "BETTER_AUTH_GOOGLE_CLIENT_ID", "BETTER_AUTH_GOOGLE_CLIENT_SECRET",
  "GMAIL_GOOGLE_CLIENT_ID", "GMAIL_GOOGLE_CLIENT_SECRET", "GMAIL_PUBSUB_TOPIC",
  "GOOGLE_PUBSUB_PUSH_AUDIENCE", "GOOGLE_PUBSUB_PUSH_SERVICE_ACCOUNT_EMAIL",
  "GOOGLE_PUBSUB_SUBSCRIPTION", "TOKEN_ENCRYPTION_KEY", "OPENAI_WEBHOOK_SECRET",
] as const;

export const WORKER_RUNTIME_KEYS = [
  "DATABASE_URL", "TEMPORAL_ADDRESS", "TEMPORAL_NAMESPACE", "TEMPORAL_API_KEY",
  "GMAIL_GOOGLE_CLIENT_ID", "GMAIL_GOOGLE_CLIENT_SECRET", "GMAIL_PUBSUB_TOPIC",
  "TOKEN_ENCRYPTION_KEY", "OPENAI_API_KEY", "OPENAI_WEBHOOK_SECRET",
] as const;

export type RuntimeEnvironmentKey =
  | (typeof API_RUNTIME_KEYS)[number]
  | (typeof WORKER_RUNTIME_KEYS)[number];

export const RUNTIME_KEYS: readonly RuntimeEnvironmentKey[] = [
  ...new Set<RuntimeEnvironmentKey>([...API_RUNTIME_KEYS, ...WORKER_RUNTIME_KEYS]),
];

export type RuntimeEnvironment = Record<RuntimeEnvironmentKey, string>;
