export {
  createGmailDraft,
  createGmailLabel,
  deleteGmailDraft,
  deleteGmailLabel,
  getGmailDraft,
  getGmailLabel,
  getGmailMessage,
  getGmailMessageState,
  getGmailProfile,
  gmailHistoryChanges,
  GmailApiError,
  GOOGLE_REAUTHENTICATION_REQUIRED_ERROR_CODE,
  isGoogleReauthenticationRequired,
  listGmailDrafts,
  listGmailHistory,
  listGmailLabels,
  listGmailMessages,
  modifyGmailMessageLabels,
  refreshGoogleAccessToken,
  startGmailWatch,
  stopGmailWatch,
  trashGmailMessage,
  untrashGmailMessage,
  updateGmailDraft,
  updateGmailLabel,
  type GmailDraft,
  type GmailDraftPage,
  type GmailDraftReference,
  type GmailDraftWrite,
  type GmailHistoryChange,
  type GmailHistoryPage,
  type GmailHistoryRecord,
  type GmailLabel,
  type GmailLabelInput,
  type GmailMessagePage,
  type GmailMessageReference,
  type GmailMessageState,
  type GmailProfile,
  type GmailRawMessage,
  type GmailWatchResponse,
} from "./client";
export {
  composePlainTextGmailMessage,
  composePlainTextGmailReply,
} from "./draft";
export {
  extractEmailAddress,
  isMemoryEligible,
  parseGmailMessage,
  type ParsedGmailAttachment,
  type ParsedGmailHeader,
  type ParsedGmailMessage,
} from "./message";
export {
  createGoogleAuthorizationRequest,
  exchangeGoogleAuthorizationCode,
  verifyGoogleIdToken,
  type GoogleAuthorizationRequest,
  type GoogleAuthorizationResult,
  type VerifiedGoogleIdTokenClaims,
} from "./oauth";
export { GMAIL_SCOPE_DESCRIPTION, GMAIL_SCOPES } from "./scopes";
